const $=s=>document.querySelector(s);
const pieces=[],components=[];let project=null,scene,camera,renderer,controls,group;
const BOARD_W=184,BOARD_H=275,KERF=.3;
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function piece(d={}){pieces.push({name:d.name||'',w:d.w||'',h:d.h||'',q:d.q||1});renderPieces()}
function renderPieces(){$('#pieces').innerHTML=pieces.map((p,i)=>`<div class="piece"><input placeholder="Nome da peça" value="${esc(p.name)}" oninput="pieces[${i}].name=this.value"><input type="number" min="1" step="0.1" placeholder="Largura cm" value="${p.w}" oninput="pieces[${i}].w=this.value"><input type="number" min="1" step="0.1" placeholder="Comprimento cm" value="${p.h}" oninput="pieces[${i}].h=this.value"><input type="number" min="1" value="${p.q}" oninput="pieces[${i}].q=this.value"><button onclick="pieces.splice(${i},1);renderPieces()">×</button></div>`).join('')}
function comp(){components.push({name:'',q:1});renderComp()}
function renderComp(){$('#components').innerHTML=components.map((c,i)=>`<div class="comp"><input placeholder="Puxador, pé, rodízio..." value="${esc(c.name)}" oninput="components[${i}].name=this.value"><input type="number" min="1" value="${c.q}" oninput="components[${i}].q=this.value"><button onclick="components.splice(${i},1);renderComp()">×</button></div>`).join('')}
piece({name:'Lateral esquerda'});piece({name:'Lateral direita'});$('#add').onclick=()=>piece();$('#addComp').onclick=comp;
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='cut'&&project)drawCut();if(id==='view3d'&&project)setTimeout(init3d,30)}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#go3d').onclick=()=>go('view3d');
function normalize(){return pieces.filter(p=>+p.w>0&&+p.h>0).map((p,i)=>({id:i,name:p.name||`Peça ${i+1}`,w:+p.w,h:+p.h,q:Math.max(1,Math.floor(+p.q||1))}))}
$('#confirm').onclick=()=>{const ps=normalize();if(!ps.length)return alert('Adicione pelo menos uma peça com medidas.');if(ps.some(p=>p.w>BOARD_W&&p.w>BOARD_H||p.h>BOARD_W&&p.h>BOARD_H))return alert('Há uma peça maior que a chapa de 184 × 275 cm.');project={name:$('#name').value.trim()||'Móvel',desc:$('#desc').value.trim(),pieces:ps,components:components.map(c=>({name:c.name,q:+c.q||1})),boards:pack(ps)};go('cut')};
function pack(ps){const items=[];ps.forEach(p=>{for(let n=1;n<=p.q;n++)items.push({...p,instance:n})});items.sort((a,b)=>Math.max(b.w,b.h)*Math.min(b.w,b.h)-Math.max(a.w,a.h)*Math.min(a.w,a.h));const boards=[];for(const it of items){let ok=false;for(const b of boards){const s=spot(b,it);if(s){b.parts.push({...it,...s});ok=true;break}}if(!ok){const b={parts:[]},s=spot(b,it);if(!s)throw Error('Peça não cabe na chapa.');b.parts.push({...it,...s});boards.push(b)}}return boards}
function spot(b,it){for(const o of [{w:it.w,h:it.h,rot:false},{w:it.h,h:it.w,rot:true}]){if(o.w>BOARD_W||o.h>BOARD_H)continue;const c=[[0,0]];b.parts.forEach(p=>{c.push([p.x+p.w+KERF,p.y],[p.x,p.y+p.h+KERF])});for(const [x,y] of c){if(x+o.w>BOARD_W||y+o.h>BOARD_H)continue;const hit=b.parts.some(p=>x<p.x+p.w+KERF&&x+o.w+KERF>p.x&&y<p.y+p.h+KERF&&y+o.h+KERF>p.y);if(!hit)return{x,y,w:o.w,h:o.h,rot:o.rot}}}}return null}
function fmt(n){return Number(n).toLocaleString('pt-BR',{maximumFractionDigits:1})}
function drawCut(){const c=$('#canvas'),ctx=c.getContext('2d'),max=Math.min(1100,c.parentElement.clientWidth-4),s=max/BOARD_W;c.width=Math.round(BOARD_W*s);c.height=Math.round(BOARD_H*s);ctx.fillStyle='#eee1c8';ctx.fillRect(0,0,c.width,c.height);const colors=['#a8d5b5','#e0c27b','#9dbbd6','#c6a6d9','#d99d9d','#b9c58d'];project.boards.forEach((b,bi)=>b.parts.forEach((p,pi)=>{ctx.fillStyle=colors[(pi+bi)%colors.length];ctx.fillRect(p.x*s,p.y*s,p.w*s,p.h*s);ctx.strokeStyle='#263229';ctx.strokeRect(p.x*s,p.y*s,p.w*s,p.h*s);ctx.fillStyle='#18231b';ctx.font=`bold ${Math.max(10,12*s)}px system-ui`;ctx.fillText(p.name,p.x*s+4,p.y*s+15);ctx.font=`${Math.max(9,10*s)}px system-ui`;ctx.fillText(`${fmt(p.w)} × ${fmt(p.h)} cm${p.rot?' ↻':''}`,p.x*s+4,p.y*s+30)}));$('#summary').textContent=`${project.name} • ${project.boards.length} chapa(s) • margem de corte ${KERF} cm`;$('#legend').innerHTML=project.boards.map((b,i)=>`<div class="boardInfo"><b>Chapa ${i+1}</b> — ${b.parts.length} peça(s): ${b.parts.map(p=>`${esc(p.name)} ${fmt(p.w)}×${fmt(p.h)}`).join(' • ')}</div>`).join('')}
$('#voice').onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert('Reconhecimento de voz indisponível neste navegador.');const r=new R();r.lang='pt-BR';r.onstart=()=>$('#voiceStatus').textContent=' Ouvindo...';r.onresult=e=>{const t=e.results[0][0].transcript;$('#voiceStatus').textContent=' ✓ '+t;parseVoice(t)};r.onerror=()=>$('#voiceStatus').textContent=' Não consegui entender.';r.start()};
function parseVoice(text){const t=text.toLowerCase().replace(/,/g,'.'),m=[...t.matchAll(/(\d+(?:\.\d+)?)\s*(?:por|x|×)\s*(\d+(?:\.\d+)?)/g)];if(m.length){m.forEach((x,i)=>piece({name:`Peça ${i+1}`,w:x[1],h:x[2],q:1}));if(!$('#name').value)$('#name').value='Móvel';renderPieces()}else if(!$('#name').value)$('#name').value=text}
function init3d(){const el=$('#viewer');if(renderer){resize3d();build3d();return}scene=new THREE.Scene();scene.background=new THREE.Color(0x090d0a);camera=new THREE.PerspectiveCamera(45,el.clientWidth/el.clientHeight,.1,1000);camera.position.set(7,5,8);renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(el.clientWidth,el.clientHeight);el.innerHTML='';el.appendChild(renderer.domElement);scene.add(new THREE.HemisphereLight(0xffffff,0x33443a,2));const l=new THREE.DirectionalLight(0xffffff,2);l.position.set(6,10,7);scene.add(l);if(THREE.OrbitControls){controls=new THREE.OrbitControls(camera,renderer.domElement);controls.enableDamping=true}build3d();animate();addEventListener('resize',resize3d)}
function build3d(){if(!project)return;if(group)scene.remove(group);group=new THREE.Group();const wood=new THREE.MeshStandardMaterial({color:0x9a6b45,roughness:.72}),dark=new THREE.MeshStandardMaterial({color:0x5b3c27,roughness:.8});const ps=project.pieces,maxH=Math.max(...ps.map(p=>Math.max(p.w,p.h)),180),maxW=Math.max(...ps.map(p=>Math.min(p.w,p.h)),60),H=Math.min(6,Math.max(3.5,maxH/30)),W=Math.min(7,Math.max(2.8,maxW/25)),D=Math.max(1.8,Math.min(3.2,W*.38));const box=(w,h,d,x,y,z,m=wood)=>{const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);o.position.set(x,y,z);group.add(o)};const t=.1;box(W,t,D,0,0,D/2,dark);box(W,t,D,0,H,D/2,dark);box(t,H,D,-W/2,H/2,D/2);box(t,H,D,W/2,H/2,D/2);const shelves=Math.min(5,Math.max(0,ps.length-2));for(let i=0;i<shelves;i++)box(W-.2,t,D-.15,0,(i+1)*H/(shelves+1),D/2);const dw=(W-.12)/2;box(dw-.04,H-.18,.1,-dw/2-.02,H/2,.03);box(dw-.04,H-.18,.1,dw/2+.02,H/2,.03);group.position.y=-H/2;scene.add(group);if(controls){controls.target.set(0,0,1);controls.update()}}
function animate(){requestAnimationFrame(animate);controls?.update();renderer?.render(scene,camera)}function resize3d(){const e=$('#viewer');if(!camera||!renderer)return;camera.aspect=e.clientWidth/e.clientHeight;camera.updateProjectionMatrix();renderer.setSize(e.clientWidth,e.clientHeight)}$('#reset').onclick=()=>{if(!camera)return;camera.position.set(7,5,8);controls?.target.set(0,0,1);controls?.update()};
