const $=s=>document.querySelector(s),pieces=[],components=[];let project=null,angle=-25;const BW=184,BH=275,K=.3;
function esc(v){return String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function renderPieces(){$('#pieces').innerHTML=pieces.map((p,i)=>`<div class="piece"><input placeholder="Nome da peça" value="${esc(p.name)}" oninput="pieces[${i}].name=this.value"><input type="number" min=".1" step=".1" placeholder="cm" value="${p.w}" oninput="pieces[${i}].w=this.value"><input type="number" min=".1" step=".1" placeholder="cm" value="${p.h}" oninput="pieces[${i}].h=this.value"><input type="number" min="1" value="${p.q}" oninput="pieces[${i}].q=this.value"><button onclick="pieces.splice(${i},1);renderPieces()">×</button></div>`).join('')}
function addPiece(d={}){pieces.push({name:d.name||'',w:d.w||'',h:d.h||'',q:d.q||1});renderPieces()}function renderComp(){$('#components').innerHTML=components.map((c,i)=>`<div class="comp"><input placeholder="Puxador, pé, rodízio..." value="${esc(c.name)}" oninput="components[${i}].name=this.value"><input type="number" min="1" value="${c.q}" oninput="components[${i}].q=this.value"><button onclick="components.splice(${i},1);renderComp()">×</button></div>`).join('')}function addComp(){components.push({name:'',q:1});renderComp()}
addPiece({name:'Lateral esquerda'});addPiece({name:'Lateral direita'});$('#add').onclick=()=>addPiece();$('#addComp').onclick=addComp;
function go(id){if(id!=='project'&&!project){alert('Cadastre as peças e toque em Calcular projeto.');return}document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');if(id==='cut')drawCut();if(id==='view3d')build3d()}document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$('#go3d').onclick=()=>go('view3d');
function norm(){return pieces.filter(p=>+p.w>0&&+p.h>0).map((p,i)=>({name:p.name||`Peça ${i+1}`,w:+p.w,h:+p.h,q:Math.max(1,Math.floor(+p.q||1))}))}
$('#confirm').onclick=()=>{try{const ps=norm();if(!ps.length){alert('Informe largura e comprimento de pelo menos uma peça.');return}const bad=ps.find(p=>(p.w>BW&&p.h>BW)||(p.w>BH&&p.h>BH));if(bad){alert(`A peça "${bad.name}" não cabe na chapa de 184 × 275 cm.`);return}project={name:$('#name').value.trim()||'Móvel',desc:$('#desc').value.trim(),pieces:ps,components:components.filter(c=>c.name.trim()).map(c=>({name:c.name.trim(),q:+c.q||1})),boards:pack(ps)};go('cut')}catch(e){alert(e.message)}};
function pack(ps){const items=[];ps.forEach(p=>{for(let i=1;i<=p.q;i++)items.push({...p,instance:i})});items.sort((a,b)=>b.w*b.h-a.w*a.h);const boards=[];for(const it of items){let done=false;for(const b of boards){const s=spot(b,it);if(s){b.parts.push({...it,...s});done=true;break}}if(!done){const b={parts:[]},s=spot(b,it);if(!s)throw Error(`A peça "${it.name}" não cabe em uma chapa.`);b.parts.push({...it,...s});boards.push(b)}}return boards}
function spot(b,it){const opts=[{w:it.w,h:it.h,rot:false},{w:it.h,h:it.w,rot:true}],c=[[0,0]];b.parts.forEach(p=>{c.push([p.x+p.w+K,p.y],[p.x,p.y+p.h+K])});for(const o of opts){if(o.w>BW||o.h>BH)continue;for(const [x,y] of c){if(x+o.w>BW||y+o.h>BH)continue;if(!b.parts.some(p=>x<p.x+p.w+K&&x+o.w+K>p.x&&y<p.y+p.h+K&&y+o.h+K>p.y))return{x,y,w:o.w,h:o.h,rot:o.rot}}}return null}
function fmt(n){return Number(n).toLocaleString('pt-BR',{maximumFractionDigits:1})}function drawCut(){const root=$('#boards');root.innerHTML='';$('#summary').textContent=`${project.name} • ${project.boards.length} chapa(s) • margem ${K} cm`;project.boards.forEach((b,bi)=>{const sec=document.createElement('div');sec.className='board';sec.innerHTML=`<h3>Chapa ${bi+1} — 184 × 275 cm</h3><div class="sheet"></div>`;const sh=sec.querySelector('.sheet');b.parts.forEach(p=>{const d=document.createElement('div');d.className='part';d.style.left=p.x/BW*100+'%';d.style.top=p.y/BH*100+'%';d.style.width=p.w/BW*100+'%';d.style.height=p.h/BH*100+'%';d.innerHTML=`<b>${esc(p.name)}</b><span>${fmt(p.w)} × ${fmt(p.h)} cm${p.rot?' ↻':''}</span>`;sh.appendChild(d)});root.appendChild(sec)});$('#legend').innerHTML=project.boards.map((b,i)=>`<div class="boardInfo"><b>Chapa ${i+1}:</b> ${b.parts.length} peça(s) • ${b.parts.map(p=>`${esc(p.name)} ${fmt(p.w)}×${fmt(p.h)}`).join(' • ')}</div>`).join('')}
$('#voice').onclick=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){alert('Reconhecimento de voz indisponível. Preencha as medidas manualmente.');return}const r=new R();r.lang='pt-BR';r.onstart=()=>$('#voiceStatus').textContent=' Ouvindo...';r.onresult=e=>{const t=e.results[0][0].transcript;$('#voiceStatus').textContent=' ✓ '+t;parseVoice(t)};r.onerror=()=>$('#voiceStatus').textContent=' Não consegui entender.';r.start()};function parseVoice(t){const s=t.toLowerCase().replace(/,/g,'.'),m=[...s.matchAll(/(\d+(?:\.\d+)?)\s*(?:por|x|×)\s*(\d+(?:\.\d+)?)/g)];if(!m.length){if(!$('#name').value)$('#name').value=t;return}m.forEach((x,i)=>addPiece({name:`Peça ${i+1}`,w:x[1],h:x[2],q:1}));if(!$('#name').value)$('#name').value='Móvel'}
function build3d(){const v=$('#viewer');v.innerHTML='<div id="cabinet" class="cabinet"><div class="face front"><div class="door l"><i class="handle"></i></div><div class="door r"><i class="handle"></i></div></div><div class="face back"></div><div class="face side leftSide"></div><div class="face side rightSide"></div><div class="face topFace"></div><div class="face bottomFace"></div></div>';const c=$('#cabinet');c.style.transform=`translate(-50%,-50%) rotateY(${angle}deg)`;$('#modelInfo').textContent=`${project.pieces.length} tipos de peça • ${project.boards.length} chapa(s) • ${project.components.length} componente(s)`}function rotate(n){angle+=n;const c=$('#cabinet');if(c)c.style.transform=`translate(-50%,-50%) rotateY(${angle}deg)`}$('#left').onclick=()=>rotate(-25);$('#right').onclick=()=>rotate(25);$('#reset').onclick=()=>{angle=-25;build3d()};